import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import { Users, Lock, Mail, ArrowRight, UserCircle, UserPlus, LogIn, TreeDeciduous } from 'lucide-react';

// Using the generated image path
const BG_IMAGE = "https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=2070&auto=format&fit=crop";
// Note: In a real environment I'd use the local path, but for demonstration 
// and reliability across renders without local asset server issues,
// I will use the path I just generated by referencing the artifact if possible or a high-quality placeholder.
// Actually, I'll use the local path if I can determine it, but since I can't easily reference 
// the UUID path in code without it being brittle, I'll use a CSS variable or similar.
// For now, I will use a high-quality family-themed placeholder that matches the aesthetic.

const LoginScreen = () => {
    const [isRegister, setIsRegister] = useState(false);
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const { login, register, loginAsGuest, isAuthLoading } = useAuth();
    const toast = useToast();

    const handleSubmit = async (e) => {
        e.preventDefault();

        let result;
        if (isRegister) {
            result = await register(name, email, password);
            if (result.success) {
                toast.success("Akun berhasil dibuat! Silakan masuk.");
                setIsRegister(false);
                setPassword('');
            }
        } else {
            result = await login(email, password);
            if (result.success) {
                toast.success("Selamat datang kembali!");
            }
        }

        if (result && !result.success) {
            toast.error(result.message);
        }
    };

    return (
        <div className="min-h-screen w-full flex items-center justify-center p-4 relative overflow-hidden font-sans">
            {/* Ambient Background with Generated Image Feel */}
            <div
                className="absolute inset-0 bg-cover bg-center transition-transform duration-[10s] scale-110 animate-pulse-slow"
                style={{
                    backgroundImage: `url('https://images.unsplash.com/photo-1464692805480-a69dfaafdb0d?q=80&w=2070&auto=format&fit=crop')`,
                    filter: 'brightness(0.4) saturate(1.2)'
                }}
            />

            {/* Animated Blurs */}
            <div className="absolute top-[-10%] right-[-10%] w-[50%] h-[50%] bg-blue-500/20 rounded-full blur-[120px] animate-pulse"></div>
            <div className="absolute bottom-[-10%] left-[-10%] w-[50%] h-[50%] bg-amber-500/10 rounded-full blur-[120px] animate-pulse" style={{ animationDelay: '2s' }}></div>

            <div className="w-full max-w-5xl grid lg:grid-cols-2 gap-0 relative z-10 bg-white/5 dark:bg-slate-900/40 backdrop-blur-2xl rounded-3xl overflow-hidden border border-white/10 shadow-[0_32px_64px_-16px_rgba(0,0,0,0.5)]">

                {/* Visual Section - Visible on LG */}
                <div className="hidden lg:flex flex-col justify-between p-12 bg-gradient-to-br from-blue-600/20 to-transparent border-r border-white/5">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center shadow-lg">
                            <TreeDeciduous className="text-blue-600" size={24} />
                        </div>
                        <span className="text-xl font-bold text-white tracking-tight">Family Archive</span>
                    </div>

                    <div className="space-y-6">
                        <h2 className="text-5xl font-extrabold text-white leading-tight">
                            Abadikan <br />
                            <span className="text-blue-400">Warisan</span> <br />
                            Keluarga Anda.
                        </h2>
                        <p className="text-slate-300 text-lg max-w-md leading-relaxed">
                            Satukan potongan sejarah, simpan kenangan berharga, dan hubungkan generasi di satu tempat yang aman dan elegan.
                        </p>
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="flex -space-x-3">
                            {[1, 2, 3, 4].map(i => (
                                <div key={i} className="w-10 h-10 rounded-full border-2 border-slate-900 bg-slate-800 flex items-center justify-center overflow-hidden">
                                    <img src={`https://i.pravatar.cc/100?img=${i + 10}`} alt="user" />
                                </div>
                            ))}
                        </div>
                        <span className="text-sm text-slate-400 font-medium">Bergabung bersama 500+ keluarga lainnya</span>
                    </div>
                </div>

                {/* Form Section */}
                <div className="p-8 lg:p-12 flex flex-col justify-center bg-white/80 dark:bg-slate-900/80 backdrop-blur-md">
                    <div className="mb-8 block lg:hidden">
                        <div className="flex items-center gap-2 mb-2">
                            <TreeDeciduous className="text-blue-600" size={24} />
                            <span className="text-xl font-bold tracking-tight dark:text-white">Family Archive</span>
                        </div>
                    </div>

                    <div className="mb-10">
                        <h3 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">
                            {isRegister ? 'Buat Akun' : 'Selamat Datang'}
                        </h3>
                        <p className="text-slate-500 dark:text-slate-400">
                            {isRegister ? 'Mulailah membangun silsilah keluarga Anda sekarang.' : 'Masuk untuk mengelola data keluarga Anda.'}
                        </p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-4">
                        {isRegister && (
                            <div className="space-y-1.5 transform animate-in slide-in-from-top-4 fade-in duration-300">
                                <label className="text-xs font-bold uppercase tracking-wider text-slate-500 ml-1">Nama Lengkap</label>
                                <div className="relative group">
                                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-slate-400">
                                        <UserCircle size={18} />
                                    </div>
                                    <input
                                        type="text"
                                        value={name}
                                        onChange={(e) => setName(e.target.value)}
                                        placeholder="Nama sesuai KTP"
                                        className="w-full pl-11 pr-4 py-3.5 bg-slate-100 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 outline-none transition-all dark:text-white font-medium"
                                        required
                                    />
                                </div>
                            </div>
                        )}

                        <div className="space-y-1.5">
                            <label className="text-xs font-bold uppercase tracking-wider text-slate-500 ml-1">Alamat Email</label>
                            <div className="relative group">
                                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-slate-400">
                                    <Mail size={18} />
                                </div>
                                <input
                                    type="email"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                    placeholder="email@keluarga.com"
                                    className="w-full pl-11 pr-4 py-3.5 bg-slate-100 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 outline-none transition-all dark:text-white font-medium"
                                    required
                                />
                            </div>
                        </div>

                        <div className="space-y-1.5">
                            <label className="text-xs font-bold uppercase tracking-wider text-slate-500 ml-1">Kata Sandi</label>
                            <div className="relative group">
                                <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-slate-400">
                                    <Lock size={18} />
                                </div>
                                <input
                                    type="password"
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="Minimal 6 karakter"
                                    className="w-full pl-11 pr-4 py-3.5 bg-slate-100 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-blue-500 outline-none transition-all dark:text-white font-medium"
                                    required
                                />
                            </div>
                        </div>

                        <div className="pt-2">
                            <button
                                type="submit"
                                disabled={isAuthLoading}
                                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-2xl shadow-xl shadow-blue-500/30 transition-all hover:scale-[1.01] active:scale-[0.98] flex items-center justify-center gap-2 group disabled:opacity-70 disabled:grayscale"
                            >
                                {isAuthLoading ? (
                                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                                ) : (
                                    <>
                                        {isRegister ? 'Daftar Sekarang' : 'Masuk ke Dashboard'}
                                        <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                                    </>
                                )}
                            </button>
                        </div>
                    </form>

                    <div className="mt-8 text-center flex items-center justify-center gap-2 text-slate-500 dark:text-slate-400 text-sm">
                        <span>{isRegister ? 'Sudah memiliki akun?' : 'Baru di sini?'}</span>
                        <button
                            onClick={() => setIsRegister(!isRegister)}
                            className="text-blue-600 dark:text-blue-400 font-bold hover:underline"
                        >
                            {isRegister ? 'Masuk Saja' : 'Buat Akun Baru'}
                        </button>
                    </div>

                    <div className="relative my-10 px-10">
                        <div className="absolute inset-0 flex items-center px-10">
                            <div className="w-full border-t border-slate-200 dark:border-slate-700/50"></div>
                        </div>
                        <div className="relative flex justify-center text-[10px] uppercase tracking-widest font-bold">
                            <span className="bg-white/80 dark:bg-slate-900/80 backdrop-blur rounded-full px-4 text-slate-400">Atau Akses Cepat</span>
                        </div>
                    </div>

                    <button
                        onClick={() => {
                            loginAsGuest();
                            toast.info("Masuk sebagai Tamu");
                        }}
                        className="w-full bg-transparent border-2 border-slate-200 dark:border-slate-700 hover:border-blue-500/50 hover:bg-blue-50/10 dark:hover:bg-blue-500/5 text-slate-600 dark:text-slate-300 font-bold py-3.5 rounded-2xl transition-all flex items-center justify-center gap-3 group"
                    >
                        <UserCircle size={20} className="text-slate-400 group-hover:text-blue-500 transition-colors" />
                        Lanjutkan sebagai Tamu
                    </button>

                    <p className="text-center text-[10px] text-slate-400 mt-10 uppercase tracking-widest font-medium">
                        &copy; {new Date().getFullYear()} Family Archive &bull; Digital Heritage
                    </p>
                </div>
            </div>
        </div>
    );
};

export default LoginScreen;
